Repository DONGA-ST-A/Backend, pull requests merged in 2023-09, with the labels that each got.

#10 [Feature] BaseTimeEntity 생성 및 적용
  src/main/java/com/teamA/hicardi/HicardiApplication.java
  src/main/java/com/teamA/hicardi/common/entity/BaseTimeEntity.java
Labels: ✨ Feature

#12 [Feature] ResponseDto 생성 및 Error 관련 코드 추가
  src/main/java/com/teamA/hicardi/common/dto/ResponseDto.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
  src/main/java/com/teamA/hicardi/error/dto/ErrorResponse.java
  src/main/java/com/teamA/hicardi/error/exception/GlobalExceptionHandler.java
  src/main/java/com/teamA/hicardi/error/exception/custom/BusinessException.java
  src/main/java/com/teamA/hicardi/error/exception/custom/TokenException.java
Labels: ✨ Feature

#14 [Feature] Entity 생성 및 필드 추가
  src/main/java/com/teamA/hicardi/domain/cart/entity/Cart.java
  src/main/java/com/teamA/hicardi/domain/cartItem/entity/CartItem.java
  src/main/java/com/teamA/hicardi/domain/faq/entity/Category.java
  src/main/java/com/teamA/hicardi/domain/faq/entity/Faq.java
  src/main/java/com/teamA/hicardi/domain/item/entity/Item.java
  src/main/java/com/teamA/hicardi/domain/item/entity/ItemImage.java
  src/main/java/com/teamA/hicardi/domain/item/entity/SellStatus.java
  src/main/java/com/teamA/hicardi/domain/member/entity/Member.java
  src/main/java/com/teamA/hicardi/domain/notice/entity/Notice.java
  src/main/java/com/teamA/hicardi/domain/question/entity/Question.java
Labels: ✨ Feature

#17 [Feature] Spring Security 인증/인가 구현
  .github/workflows/dev-deploy.yml
  build.gradle
  docker-compose.yml
  src/main/java/com/teamA/hicardi/config/RedisConfig.java
  src/main/java/com/teamA/hicardi/config/SecurityConfig.java
  src/main/java/com/teamA/hicardi/domain/auth/controller/AuthController.java
  src/main/java/com/teamA/hicardi/domain/auth/dto/request/SignUpRequestDto.java
  src/main/java/com/teamA/hicardi/domain/auth/filter/CustomJsonAuthenticationFilter.java
  src/main/java/com/teamA/hicardi/domain/auth/handler/LoginFailureHandler.java
  src/main/java/com/teamA/hicardi/domain/auth/handler/LoginSuccessHandler.java
  src/main/java/com/teamA/hicardi/domain/auth/service/AuthService.java
  src/main/java/com/teamA/hicardi/domain/auth/service/LoginService.java
  src/main/java/com/teamA/hicardi/domain/member/entity/Member.java
  src/main/java/com/teamA/hicardi/domain/member/repository/MemberRepository.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
  src/main/java/com/teamA/hicardi/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/teamA/hicardi/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/teamA/hicardi/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/teamA/hicardi/jwt/service/JwtService.java
  src/main/java/com/teamA/hicardi/util/PasswordUtil.java
  src/main/java/com/teamA/hicardi/util/RedisUtil.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#19 docker-compose.yml nginx 코드 삭제
  docker-compose.yml
Labels: 🌏 Deploy

#21 [Feature] 로그인 시 회원 아이디로 로그인하도록 변경
  src/main/java/com/teamA/hicardi/domain/auth/dto/request/SignUpRequestDto.java
  src/main/java/com/teamA/hicardi/domain/auth/filter/CustomJsonAuthenticationFilter.java
  src/main/java/com/teamA/hicardi/domain/auth/handler/LoginFailureHandler.java
  src/main/java/com/teamA/hicardi/domain/auth/handler/LoginSuccessHandler.java
  src/main/java/com/teamA/hicardi/domain/auth/service/AuthService.java
  src/main/java/com/teamA/hicardi/domain/auth/service/LoginService.java
  src/main/java/com/teamA/hicardi/domain/member/repository/MemberRepository.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
  src/main/java/com/teamA/hicardi/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/teamA/hicardi/jwt/service/JwtService.java
Labels: ✨ Feature

#25 [Setting] AWS S3 설정
  build.gradle
  src/main/java/com/teamA/hicardi/common/s3/FileService.java
  src/main/java/com/teamA/hicardi/config/S3Config.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
Labels: ⚙ Setting

#27 [Feature] 로그아웃 기능 구현
  src/main/java/com/teamA/hicardi/domain/auth/controller/AuthController.java
  src/main/java/com/teamA/hicardi/domain/auth/service/AuthService.java
Labels: ✨ Feature

#29 [Feature] 로그인 시 Bearer 포함해 헤더에 Access Token 담기
  src/main/java/com/teamA/hicardi/jwt/service/JwtService.java
Labels: ✨ Feature

#31 [Setting] Swagger 설정
  build.gradle
  src/main/java/com/teamA/hicardi/HicardiApplication.java
  src/main/java/com/teamA/hicardi/config/SwaggerConfig.java
Labels: ⚙ Setting

#32 [Refactor] 장바구니 상품 추가 Dto 클래스 타입 record로 변경 및 ErrorCode 추가
  src/main/java/com/teamA/hicardi/domain/cart/controller/CartController.java
  src/main/java/com/teamA/hicardi/domain/cart/repository/CartRepository.java
  src/main/java/com/teamA/hicardi/domain/cart/service/CartService.java
  src/main/java/com/teamA/hicardi/domain/cartItem/dto/CartItemAddRequestDto.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
  src/test/java/com/teamA/hicardi/domain/cart/controller/CartControllerTest.java
  src/test/java/com/teamA/hicardi/utils/TestUserArgumentResolver.java
Labels: 🔨 Refactor

#34 [Test] AuthController 테스트 코드 추가 및 스웨거 명세 작성
  src/main/java/com/teamA/hicardi/domain/auth/controller/AuthController.java
  src/test/java/com/teamA/hicardi/domain/auth/controller/AuthControllerTest.java
Labels: 📃 Docs, ✅ Test

#36 [Feature] FAQ 생성 기능 구현
  src/main/java/com/teamA/hicardi/config/SecurityConfig.java
  src/main/java/com/teamA/hicardi/domain/faq/controller/FaqController.java
  src/main/java/com/teamA/hicardi/domain/faq/dto/request/FaqSaveRequestDto.java
  src/main/java/com/teamA/hicardi/domain/faq/entity/Category.java
  src/main/java/com/teamA/hicardi/domain/faq/entity/Faq.java
  src/main/java/com/teamA/hicardi/domain/faq/repository/FaqRepository.java
  src/main/java/com/teamA/hicardi/domain/faq/service/FaqService.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
  src/main/java/com/teamA/hicardi/error/exception/GlobalExceptionHandler.java
  src/test/java/com/teamA/hicardi/domain/faq/controller/FaqControllerTest.java
Labels: ✨ Feature

#39 [Feature] FAQ 전체 조회 기능 구현
  src/main/java/com/teamA/hicardi/common/dto/PageResponseDto.java
  src/main/java/com/teamA/hicardi/config/SecurityConfig.java
  src/main/java/com/teamA/hicardi/domain/faq/controller/FaqController.java
  src/main/java/com/teamA/hicardi/domain/faq/dto/response/FaqGetAllResponseDto.java
  src/main/java/com/teamA/hicardi/domain/faq/entity/Category.java
  src/main/java/com/teamA/hicardi/domain/faq/repository/FaqRepository.java
  src/main/java/com/teamA/hicardi/domain/faq/service/FaqService.java
  src/main/resources/data.sql
Labels: ✨ Feature

#41 [Feature] FAQ 카테고리별 조회 기능 구현
  src/main/java/com/teamA/hicardi/config/SecurityConfig.java
  src/main/java/com/teamA/hicardi/domain/faq/controller/FaqController.java
  src/main/java/com/teamA/hicardi/domain/faq/dto/response/FaqGetAllResponseDto.java
  src/main/java/com/teamA/hicardi/domain/faq/dto/response/FaqGetResponseDto.java
  src/main/java/com/teamA/hicardi/domain/faq/repository/FaqRepository.java
  src/main/java/com/teamA/hicardi/domain/faq/service/FaqService.java
  src/test/java/com/teamA/hicardi/domain/faq/controller/FaqControllerTest.java
Labels: ✨ Feature

#42 상품 Entity 수정
  src/main/java/com/teamA/hicardi/domain/item/converter/SetTagConverter.java
  src/main/java/com/teamA/hicardi/domain/item/entity/Item.java
  src/main/java/com/teamA/hicardi/domain/item/entity/ItemImage.java
  src/main/java/com/teamA/hicardi/domain/item/entity/SellStatus.java
  src/main/java/com/teamA/hicardi/domain/item/entity/Tag.java
Labels: ✨ Feature

#44 [Refactor] FAQ 조회 시 Enum type description 반환
  src/main/java/com/teamA/hicardi/domain/faq/dto/response/FaqGetResponseDto.java
  src/main/java/com/teamA/hicardi/domain/faq/entity/Category.java
Labels: 🔨 Refactor

#46 [Feature] FAQ 키워드 검색 기능 구현
  src/main/java/com/teamA/hicardi/domain/faq/controller/FaqController.java
  src/main/java/com/teamA/hicardi/domain/faq/repository/FaqRepository.java
  src/main/java/com/teamA/hicardi/domain/faq/service/FaqService.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
  src/test/java/com/teamA/hicardi/domain/faq/controller/FaqControllerTest.java
Labels: ✨ Feature

#48 [Feature] 상품 목록 조회 기능 구현
  src/main/java/com/teamA/hicardi/config/SecurityConfig.java
  src/main/java/com/teamA/hicardi/domain/item/controller/ItemController.java
  src/main/java/com/teamA/hicardi/domain/item/converter/SetTagConverter.java
  src/main/java/com/teamA/hicardi/domain/item/dto/response/ItemGetAllResponseDto.java
  src/main/java/com/teamA/hicardi/domain/item/entity/Item.java
  src/main/java/com/teamA/hicardi/domain/item/entity/SellStatus.java
  src/main/java/com/teamA/hicardi/domain/item/repository/ItemRepository.java
  src/main/java/com/teamA/hicardi/domain/item/service/ItemService.java
  src/main/resources/data.sql
  src/test/java/com/teamA/hicardi/domain/item/controller/ItemControllerTest.java
Labels: ⚠ BugFix, ✨ Feature

#50 [Refactor] data.sql을 import.sql로 변경
  src/main/resources/import.sql
Labels: 🔨 Refactor

#52 fix: import.sql의 ITEM을 Item으로 수정
  src/main/resources/import.sql
Labels: ⚠ BugFix

#54 [Feature] 상품 상세 조회 기능 구현
  src/main/java/com/teamA/hicardi/domain/item/controller/ItemController.java
  src/main/java/com/teamA/hicardi/domain/item/dto/response/ItemGetResponseDto.java
  src/main/java/com/teamA/hicardi/domain/item/repository/ItemImageRepository.java
  src/main/java/com/teamA/hicardi/domain/item/service/ItemService.java
  src/main/resources/import.sql
  src/test/java/com/teamA/hicardi/domain/item/controller/ItemControllerTest.java
Labels: ✨ Feature

#56 [Docs] Swagger 명세 수정
  src/main/java/com/teamA/hicardi/domain/faq/controller/FaqController.java
  src/main/java/com/teamA/hicardi/domain/item/controller/ItemController.java
Labels: 📃 Docs

#58 [Refactor] Item의 Tag 필드를 Entity로 변경
  src/main/java/com/teamA/hicardi/domain/item/controller/ItemController.java
  src/main/java/com/teamA/hicardi/domain/item/converter/SetTagConverter.java
  src/main/java/com/teamA/hicardi/domain/item/dto/response/ItemGetAllResponseDto.java
  src/main/java/com/teamA/hicardi/domain/item/dto/response/ItemGetResponseDto.java
  src/main/java/com/teamA/hicardi/domain/item/dto/response/ItemsGetResponseDto.java
  src/main/java/com/teamA/hicardi/domain/item/entity/Item.java
  src/main/java/com/teamA/hicardi/domain/item/entity/ItemTag.java
  src/main/java/com/teamA/hicardi/domain/item/entity/Tag.java
  src/main/java/com/teamA/hicardi/domain/item/repository/ItemTagRepository.java
  src/main/java/com/teamA/hicardi/domain/item/service/ItemService.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
  src/main/resources/import.sql
  src/test/java/com/teamA/hicardi/domain/item/controller/ItemControllerTest.java
Labels: 🔨 Refactor

#60 [Feature] 상품 태그로 상품을 조회하는 기능 구현
  build.gradle
  src/main/java/com/teamA/hicardi/domain/faq/controller/FaqController.java
  src/main/java/com/teamA/hicardi/domain/faq/entity/Category.java
  src/main/java/com/teamA/hicardi/domain/item/controller/ItemController.java
  src/main/java/com/teamA/hicardi/domain/item/entity/Tag.java
  src/main/java/com/teamA/hicardi/domain/item/repository/ItemTagRepository.java
  src/main/java/com/teamA/hicardi/domain/item/service/ItemService.java
  src/test/java/com/teamA/hicardi/domain/faq/controller/FaqControllerTest.java
  src/test/java/com/teamA/hicardi/domain/item/controller/ItemControllerTest.java
Labels: ✨ Feature

#62 [Setting] CORS 설정
  src/main/java/com/teamA/hicardi/config/WebConfig.java
Labels: ⚙ Setting

#64 [Feature] 공지사항 전체 조회 기능 구현
  src/main/java/com/teamA/hicardi/config/SecurityConfig.java
  src/main/java/com/teamA/hicardi/domain/notice/controller/NoticeController.java
  src/main/java/com/teamA/hicardi/domain/notice/dto/response/NoticeGetResponseDto.java
  src/main/java/com/teamA/hicardi/domain/notice/entity/Notice.java
  src/main/java/com/teamA/hicardi/domain/notice/entity/NoticeCategory.java
  src/main/java/com/teamA/hicardi/domain/notice/repository/NoticeRepository.java
  src/main/java/com/teamA/hicardi/domain/notice/service/NoticeService.java
  src/main/resources/import.sql
  src/test/java/com/teamA/hicardi/domain/notice/controller/NoticeControllerTest.java
Labels: ✨ Feature

#66 [Docs] import.sql subname 수정
  src/main/resources/import.sql
Labels: 📃 Docs

#71 [Feature] 공지사항 카테고리 조회 및 검색 기능 구현
  src/main/java/com/teamA/hicardi/domain/notice/controller/NoticeController.java
  src/main/java/com/teamA/hicardi/domain/notice/entity/NoticeCategory.java
  src/main/java/com/teamA/hicardi/domain/notice/repository/NoticeRepository.java
  src/main/java/com/teamA/hicardi/domain/notice/service/NoticeService.java
  src/test/java/com/teamA/hicardi/domain/notice/controller/NoticeControllerTest.java
Labels: ✨ Feature

#73 [Feature] 공지사항 상세조회 기능 구현
  src/main/java/com/teamA/hicardi/domain/notice/controller/NoticeController.java
  src/main/java/com/teamA/hicardi/domain/notice/repository/NoticeRepository.java
  src/main/java/com/teamA/hicardi/domain/notice/service/NoticeService.java
  src/main/java/com/teamA/hicardi/error/ErrorCode.java
  src/main/resources/import.sql
  src/test/java/com/teamA/hicardi/domain/notice/controller/NoticeControllerTest.java
Labels: ✨ Feature

#75 [Refactor] 공지사항 상세 페이지 내용과 파일 응답 수정
  src/main/java/com/teamA/hicardi/domain/notice/dto/response/NoticeGetResponseDto.java
  src/main/java/com/teamA/hicardi/domain/notice/entity/Notice.java
  src/main/java/com/teamA/hicardi/domain/notice/repository/NoticeRepository.java
  src/main/java/com/teamA/hicardi/domain/notice/service/NoticeService.java
  src/main/resources/import.sql
Labels: 🔨 Refactor

#77 [Fix] 공지사항 조회수 코드 수정 및 더미데이터 수정
  src/main/java/com/teamA/hicardi/domain/notice/service/NoticeService.java
  src/main/resources/import.sql
Labels: ⚠ BugFix

#79 [Docs] 상품 이미지 추가
  src/main/resources/import.sql
Labels: 📃 Docs
